name: hello-gsm-prod-ci

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: prod
      push_to_ecr: false
    secrets:
      CLIENT_ENV_FILE: ${{ secrets.PROD_CLIENT_ENV_FILE }}
      ADMIN_ENV_FILE: ${{ secrets.PROD_ADMIN_ENV_FILE }}

  notify:
    needs: build
    uses: ./.github/workflows/reusable-notifications.yml
    with:
      workflow_name: hello-gsm prod
      workflow_type: CI
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
