name: Reusable Notifications

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
      workflow_type:
        required: true
        type: string
        description: 'CI or CD'
      success_message:
        required: false
        type: string
        default: ''
      failure_message:
        required: false
        type: string
        default: ''
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Success Discord Notification
        uses: sarisia/actions-status-discord@v1.11.0
        if: success()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          title: '✅ ${{ inputs.workflow_name }} ${{ inputs.workflow_type }}'
          status: success
          content: ${{ inputs.success_message || (inputs.workflow_type == 'CI' && 'PR을 확인해주세요.' || '배포가 성공적으로 완료되었습니다.') }}
          username: hello-gsm bot
          color: 4CAF50

      - name: Failure notification to discord
        uses: sarisia/actions-status-discord@v1.11.0
        if: failure()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          title: '❌ ${{ inputs.workflow_name }} ${{ inputs.workflow_type }}'
          content: ${{ inputs.failure_message || (inputs.workflow_type == 'CI' && '에러를 확인해주세요.' || '배포 중 에러가 발생했습니다.') }}
          status: failure
          username: hello-gsm bot
          color: e74c3c
