name: hello-gsm-stage-cd

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: stage
      push_to_ecr: true
    secrets:
      CLIENT_ENV_FILE: ${{ secrets.STAGE_CLIENT_ENV_FILE }}
      ADMIN_ENV_FILE: ${{ secrets.STAGE_ADMIN_ENV_FILE }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ECR_CLIENT_REPOSITORY: ${{ secrets.AWS_ECR_STAGE_CLIENT_REPOSITORY }}
      AWS_ECR_ADMIN_REPOSITORY: ${{ secrets.AWS_ECR_STAGE_ADMIN_REPOSITORY }}

  deploy:
    needs: build
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: stage
      client_port: '3004'
      admin_port: '3005'
      use_blue_green: false
    secrets:
      CLIENT_ENV_FILE: ${{ secrets.STAGE_CLIENT_ENV_FILE }}
      ADMIN_ENV_FILE: ${{ secrets.STAGE_ADMIN_ENV_FILE }}
      BASTION_EC2_IP: ${{ secrets.BASTION_EC2_IP }}
      BASTION_EC2_PORT: ${{ secrets.BASTION_EC2_PORT }}
      BASTION_EC2_USERNAME: ${{ secrets.BASTION_EC2_USERNAME }}
      BASTION_EC2_SSH_KEY: ${{ secrets.BASTION_EC2_SSH_KEY }}
      EC2_SSH_KEY_NAME: ${{ secrets.EC2_SSH_KEY_NAME }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_IP: ${{ secrets.EC2_IP }}
      AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}
      AWS_ECR_CLIENT_REPOSITORY: ${{ secrets.AWS_ECR_STAGE_CLIENT_REPOSITORY }}
      AWS_ECR_ADMIN_REPOSITORY: ${{ secrets.AWS_ECR_STAGE_ADMIN_REPOSITORY }}

  notify:
    needs: [build, deploy]
    uses: ./.github/workflows/reusable-notifications.yml
    with:
      workflow_name: hello-gsm stage
      workflow_type: CD
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
