name: hello-gsm-stage-ci

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: stage
      push_to_ecr: false
    secrets:
      CLIENT_ENV_FILE: ${{ secrets.STAGE_CLIENT_ENV_FILE }}
      ADMIN_ENV_FILE: ${{ secrets.STAGE_ADMIN_ENV_FILE }}

  notify:
    needs: build
    uses: ./.github/workflows/reusable-notifications.yml
    with:
      workflow_name: hello-gsm stage
      workflow_type: CI
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
